### ISSUE TITLE
README problem

### ISSUE THREAD

**Issue by wnz27** [linkedin/Iris-message-processor#1]
I think it's link: (https://github.com/linkedin/iris/tree/experimental) is invalid
u can adjust the README file

**Comment by wnz27** [comment]
on this position:
```
[Iris configurations:](https://github.com/linkedin/Iris-message-processor#iris-configurations)
Make sure you have first configured and run an instance of Iris from the [experimental-sender branch](https://github.com/linkedin/iris/tree/experimental)
```

**Comment by wnz27** [comment]
but i think u don't have this branch

**Comment by diegocepedaw** [comment]
Thanks for the heads up @wnz27, I updated the links

**Comment by wnz27** [comment]
> Thanks for the heads up @wnz27, I updated the links

ok i find the branch in project : https://github.com/linkedin/iris/tree/experimental-sender
